force-app/main/default/objects/c_ErrorLog__c/c_ErrorLog__c.object-meta.xml
<CustomObject>
    <description>Persistent storage for c_ErrorLog events. Captured by c_ErrorLog trigger filtered by setting in c_Settings.</description>
    <label>ErrorLog</label>
    <nameField>
        <label>Error</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ErrorLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/c_ErrorLog__c/fields/c_ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>c_ErrorMessage__c</fullName>
    <description>Content of the Error field from the event.</description>
    <label>ErrorMessage</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/c_ErrorLog__c/fields/c_Source__c.field-meta.xml
<CustomField>
    <fullName>c_Source__c</fullName>
    <description>Source of the event.</description>
    <label>Source</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/c_ErrorLog__c/fields/c_StackTrace__c.field-meta.xml
<CustomField>
    <fullName>c_StackTrace__c</fullName>
    <description>Content of StackTrace field from the event.</description>
    <label>StackTrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/c_ErrorLog__c/fields/c_Topic__c.field-meta.xml
<CustomField>
    <fullName>c_Topic__c</fullName>
    <description>Topic from the event.</description>
    <label>Topic</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ERR</fullName>
                <default>true</default>
                <label>ERR</label>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/c_ErrorLog.cls
public class c_ErrorLog {
    public static  c_ErrorLog__c record( String source, Exception e ) {
        c_ErrorLog__c error=new c_ErrorLog__c(
            Name = source == null ? 'unknown' : source.abbreviate( 80 )
          , c_Topic__c = e.getTypeName() == 'unknown' ? 'unknown' : e.getTypeName()
          , c_Source__c = source == null ? 'unknown' : source
          , c_ErrorMessage__c = e.getMessage() == null ? null : e.getMessage()
          , c_StackTrace__c = e.getStackTraceString() == null ? null : e.getStackTraceString()
        );
        return error;
    }
}